# GitHub actions workflow for testing tmtoolkit
# Runs tests on Ubuntu, MacOS and Windows with Python versions 3.8, 3.9 and 3.10 each, which means 9 jobs are spawned.
# Tests are run using tox (https://tox.wiki/).
#
# author: Markus Konrad <markus.konrad@wzb.eu>

name: run tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["3.2", "4.0"]
    steps:
      - uses: actions/checkout@v2
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: run tox
        run: tox -e py-${{ matrix.python-version }}-django-${{ matrix.django-version }}
